version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout:
          post:
            - '[[ ! -s "$(git rev-parse -git-dir)/shallow" ]] || git fetch -unshallow'
      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: |
            gulp build_scss
            npm run build
      - deploy:
          name: Deploy Master to Heroku
          command: |
            git add --all --force build
            git config --global user.email "circleci@thinkful.com"
            git config --global user.name "CircleCI"
            git commit -m "CircleCI: Built client bundles."
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'heroku.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==' >> ~/.ssh/known_hosts
              git push git@heroku.com:tf-ms-neutrality-client-prod.git HEAD:master --force
            fi
